### ISSUE TITLE
could not resolve host github.com

### ISSUE THREAD

**Issue by scenaristeur** [camenduru/Magic-Me-jupyter#2]
Hi thxs for all your job on all colabs you do, This kaggle does not seem to work.
could not resolve github.com

![Screenshot 2024-03-01 at 14-51-30 notebook03b061d2f5 Kaggle](https://github.com/camenduru/Magic-Me-jupyter/assets/4020744/9099fc65-6bcd-469b-a740-a3c5799fe157)

![Screenshot 2024-03-01 at 14-51-39 notebook03b061d2f5 Kaggle](https://github.com/camenduru/Magic-Me-jupyter/assets/4020744/bc90b625-a243-4e02-860a-abf7a3d29904)

**Comment by camenduru** [comment]
please first enable the internet 
![image](https://github.com/camenduru/Magic-Me-jupyter/assets/54370274/2471a8c5-b779-451e-88ca-2339fceedbda)
